FROM python:3.9-slim

WORKDIR /app
COPY client.py .

# Opcional: si tenés dependencias, copialas e instalalas
# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "client.py"]