version: '3.8'

services:
  chat-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=5000
    ports:
      - "5000:5000"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: chatdb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  nginx:
    image: nginx:latest
    depends_on:
      - chat-server
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - chat-server
    stdin_open: true    # para poder escribir en la terminal
    tty: true           # mantiene el terminal activo
    # no hace falta exponer puertos, el cliente sólo se conecta saliente

volumes:
  mysql_data: