version: '3.8'

services:
  chat-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    # opcional si querés usar logs interactivos
    stdin_open: true
    tty: true

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: chatdb
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  nginx:
    image: nginx:latest
    depends_on:
      - chat-server
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - chat-server
    stdin_open: true    # para poder escribir en la terminal
    tty: true           # mantiene el terminal activo
    # no hace falta exponer puertos, el cliente sólo se conecta saliente
  web: 
    build:
      context: ./web
    ports:
      - "5001:5000"
    depends_on:
      - mysql
    networks:
      - default 

volumes:
  mysql_data: